name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    outputs:
      pylint-score: ${{ steps.pylint.outputs.score }}
      
    steps:
    - uses: actions/checkout@v2
    - id: setup-python
      name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - id: pip-cache
      name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - id: setup-deps
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        [ -f "requirements.txt" ] && pip install -r requirements.txt
        pip install pylint coverage
    - id: pylint
      name: Analyzing the code with pylint
      run: |
        python3 -c "from pylint.lint import Run; ret = Run(['taky'], do_exit=False); print('::set-output name=score::%.2f' % ret.linter.stats['global_note'])"

